import { Logger } from './logger.js';
import { ModelManager } from './modelManager.js';
import { ConfigManager } from './configManager.js';
import { GitManager } from './gitManager.js';
import { FileManager } from './fileManager.js';
import { PromptEngine } from './promptEngine.js';

export class Agent {
  constructor({ type, modelProvider, configManager, modelManager, logger, gitManager }) {
    this.type = type;
    this.modelProvider = modelProvider;
    this.configManager = configManager;
    this.modelManager = modelManager;
    this.logger = logger;
    this.gitManager = gitManager;
    this.fileManager = new FileManager();
    this.promptEngine = new PromptEngine();
    this.config = null;
  }

  async initialize() {
    this.logger.info(`Initializing ${this.type} agent with ${this.modelProvider} provider`);
    
    // Load agent-specific configuration
    this.config = await this.configManager.getAgentConfig(this.type);
    
    // Set up model based on provider
    await this.modelManager.setProvider(this.modelProvider, this.config.model);
    
    this.logger.info('Agent initialized successfully');
  }

  async buildProject(request, options = {}) {
    this.logger.info(`Building project for request: ${request}`);
    
    // Step 1: Analyze the request
    const analysis = await this.analyzeRequest(request, options);
    
    // Step 2: Plan the project
    const plan = await this.planProject(analysis, options);
    
    // Step 3: Execute the plan
    const result = await this.executePlan(plan, options);
    
    // Step 4: Verify and finalize
    await this.finalizeProject(result, options);
    
    return result;
  }

  async analyzeRequest(request, options) {
    this.logger.info('Analyzing user request');
    
    // Use the prompt engine to create an analysis prompt
    const prompt = this.promptEngine.createAnalysisPrompt(request, options);
    
    // Get response from model
    const response = await this.modelManager.generateCompletion(prompt);
    
    // Parse the analysis
    return this.parseAnalysis(response);
  }

  async planProject(analysis, options) {
    this.logger.info('Planning project structure');
    
    const prompt = this.promptEngine.createPlanningPrompt(analysis, options);
    const response = await this.modelManager.generateCompletion(prompt);
    
    return this.parsePlan(response);
  }

  async executePlan(plan, options) {
    this.logger.info('Executing project plan');
    
    // Create project structure
    await this.fileManager.createProjectStructure(plan.structure);
    
    // Generate files
    for (const fileSpec of plan.files) {
      await this.generateFile(fileSpec, options);
    }
    
    // Install dependencies
    if (plan.dependencies && plan.dependencies.length > 0) {
      await this.fileManager.installDependencies(plan.dependencies);
    }
    
    // Set up configuration files
    await this.fileManager.setupConfigFiles(plan.configs);
    
    return { plan, status: 'executed' };
  }

  async generateFile(fileSpec, options) {
    this.logger.info(`Generating file: ${fileSpec.path}`);
    
    const prompt = this.promptEngine.createFileGenerationPrompt(fileSpec, options);
    const content = await this.modelManager.generateCompletion(prompt);
    
    await this.fileManager.writeFile(fileSpec.path, content);
  }

  async finalizeProject(result, options) {
    this.logger.info('Finalizing project');
    
    // Run tests if configured
    if (this.config.behavior.runTests) {
      await this.fileManager.runTests();
    }
    
    // Run linter if configured
    if (this.config.behavior.lintBeforeCommit) {
      await this.fileManager.runLinter();
    }
    
    // Commit changes if auto-commit is enabled
    if (this.config.behavior.autoCommit) {
      await this.gitManager.commitChanges(`feat: ${result.plan.name} project generated by agent`);
    }
    
    this.logger.info('Project finalized');
  }

  parseAnalysis(response) {
    // Simple parsing - in a real implementation, this would be more sophisticated
    return {
      type: 'project',
      description: response.substring(0, 100),
      requirements: response.split('\n').filter(line => line.trim().startsWith('-')),
      technology: this.detectTechnology(response)
    };
  }

  detectTechnology(response) {
    const techMap = {
      'javascript': ['node', 'js', 'javascript', 'es6'],
      'typescript': ['typescript', 'ts', 'tsx'],
      'python': ['python', 'py', 'django', 'flask'],
      'java': ['java', 'spring', 'maven'],
      'html': ['html', 'web', 'frontend'],
      'css': ['css', 'scss', 'sass', 'styling']
    };
    
    const lowerResponse = response.toLowerCase();
    for (const [tech, keywords] of Object.entries(techMap)) {
      if (keywords.some(keyword => lowerResponse.includes(keyword))) {
        return tech;
      }
    }
    
    return 'javascript'; // default
  }

  parsePlan(response) {
    // Simple parsing - would be more sophisticated in reality
    return {
      name: 'generated-project',
      description: 'Project generated by AI agent',
      structure: {
        src: {},
        tests: {},
        docs: {}
      },
      files: [
        {
          path: 'src/index.js',
          type: 'source',
          description: 'Main entry point'
        },
        {
          path: 'README.md',
          type: 'documentation',
          description: 'Project documentation'
        },
        {
          path: 'package.json',
          type: 'configuration',
          description: 'Project dependencies and scripts'
        }
      ],
      dependencies: [],
      configs: {}
    };
  }
}
